# A Docker Compose must always start with the version tag.
version: '3.8'

services:
  # connection string: "postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}"
  database:
    container_name: remind_database
    image: 'postgres:14.2-alpine'
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=remind_database

    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/
      - ./db:/var/lib/postgres/data/
      # - ./db-data:/var/lib/postgresql/data/

  pgadmin:
   container_name: pgadmin4_container
   image: dpage/pgadmin4:5.5
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: admin@admin.com
     PGADMIN_DEFAULT_PASSWORD: secret
     PGADMIN_LISTEN_PORT: 80
   ports:
     - 80:80
  
  server:
    build:
      context: /home/cpdev/remind/remind-backend/
      dockerfile: Dockerfile
    image: node:lts-alpine
    container_name: reminder-server
    environment:
      NODE_ENV: development
      CORSHEADER: 'http://0.0.0.0:3000'
      PROXY: 'true'
    command: npm run dev
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./remind-backend/:/logs
      - ./remind-backend/:/logs/node_modules
    depends_on:
      - database

networks:
  default:
    name: remind-network

volumes:
  db:
    driver: local