# A Docker Compose must always start with the version tag.
version: '3.8'

services:
  # connection string: "postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}"
  database:
    container_name: reminddb
    image: 'postgres:14.2-alpine'
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/
      - ./db:/var/lib/postgres/data

  server:
    image: node:17-alpine3.14
    container_name: reminder-server
    environment:
      NODE_ENV: development
      # PROXY: 'true'
    # command: npm run dev
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./remind-backend/:/logs
      - ./remind-backend/:/logs/node_modules
    depends_on:
      - database

networks:
  default:
    name: remind-network